Repository 9oormthon-project3-team2/franchise-management, pull requests merged in 2025-02, with the labels that each got.

#9 Feature/notification crud
  build.gradle
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationService.java
  src/main/java/com/goorm/friendchise/domain/notification/domain/Notification.java
  src/main/java/com/goorm/friendchise/domain/notification/domain/NotificationRepository.java
  src/main/java/com/goorm/friendchise/domain/notification/domain/NotificationTarget.java
  src/main/java/com/goorm/friendchise/domain/notification/domain/NotificationType.java
  src/main/java/com/goorm/friendchise/domain/notification/infrastructure/JpaNotificationRepository.java
  src/main/java/com/goorm/friendchise/domain/notification/infrastructure/NotificationRepositoryImpl.java
  src/main/java/com/goorm/friendchise/domain/notification/presentation/NotificationController.java
  src/main/java/com/goorm/friendchise/domain/notification/presentation/dto/NotificationCreateRequest.java
  src/main/java/com/goorm/friendchise/domain/notification/presentation/dto/NotificationResponse.java
  src/main/resources/application.yml
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationServiceTest.java
  src/test/java/com/goorm/friendchise/domain/notification/domain/NotificationTest.java
  src/test/java/com/goorm/friendchise/domain/notification/infrastructure/FakeNotificationRepository.java
Labels: feat

#6 Feature/implement manager
  src/main/java/com/goorm/friendchise/domain/manager/application/ManagerService.java
  src/main/java/com/goorm/friendchise/domain/manager/domain/Manager.java
  src/main/java/com/goorm/friendchise/domain/manager/domain/ManagerRepository.java
  src/main/java/com/goorm/friendchise/domain/manager/domain/Role.java
  src/main/java/com/goorm/friendchise/domain/manager/dto/request/ManageCreateRequest.java
  src/main/java/com/goorm/friendchise/domain/manager/dto/request/ManageLoginRequest.java
  src/main/java/com/goorm/friendchise/domain/manager/dto/response/ManagerDetailResponse.java
  src/main/java/com/goorm/friendchise/domain/manager/dto/response/ManagerPersistResponse.java
  src/main/java/com/goorm/friendchise/domain/manager/dto/response/ManagerTokenResponse.java
  src/main/java/com/goorm/friendchise/domain/manager/exception/ManagerNotFoundException.java
  src/main/java/com/goorm/friendchise/domain/manager/infrastructure/JpaManagerRepository.java
  src/main/java/com/goorm/friendchise/domain/manager/infrastructure/ManagerRepositoryImpl.java
  src/main/java/com/goorm/friendchise/domain/manager/presentation/ManagerController.java
  src/main/java/com/goorm/friendchise/global/config/SecurityConfig.java
  src/test/java/com/goorm/friendchise/domain/manager/application/ManagerServiceTest.java
  src/test/java/com/goorm/friendchise/domain/manager/domain/ManagerTest.java
  src/test/java/com/goorm/friendchise/domain/manager/infrastructure/FakeManagerRepository.java
Labels: feat

#8 Feature/ci cd
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
Labels: feat

#16 Feature/notification logic
  src/main/java/com/goorm/friendchise/FriendchiseApplication.java
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationService.java
  src/main/java/com/goorm/friendchise/domain/notification/domain/Notification.java
  src/main/java/com/goorm/friendchise/domain/notification/domain/NotificationRepository.java
  src/main/java/com/goorm/friendchise/domain/notification/domain/NotificationTarget.java
  src/main/java/com/goorm/friendchise/domain/notification/domain/NotificationType.java
  src/main/java/com/goorm/friendchise/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/goorm/friendchise/domain/notification/event/PromotionCreatedEvent.java
  src/main/java/com/goorm/friendchise/domain/notification/infrastructure/JpaNotificationRepository.java
  src/main/java/com/goorm/friendchise/domain/notification/infrastructure/NotificationRepositoryImpl.java
  src/main/java/com/goorm/friendchise/domain/notification/presentation/NotificationController.java
  src/main/java/com/goorm/friendchise/domain/notification/presentation/dto/NotificationCreateRequest.java
  src/main/java/com/goorm/friendchise/domain/promotion/application/PromotionService.java
  src/main/java/com/goorm/friendchise/domain/promotion/domain/Promotion.java
  src/main/java/com/goorm/friendchise/domain/promotion/domain/PromotionRepository.java
  src/main/java/com/goorm/friendchise/domain/promotion/dto/request/PromotionCreateRequest.java
  src/main/java/com/goorm/friendchise/domain/promotion/infrastructure/JpaPromotionRepository.java
  src/main/java/com/goorm/friendchise/domain/promotion/infrastructure/PromotionRepositoryImpl.java
  src/main/java/com/goorm/friendchise/domain/promotion/presentation/PromotionController.java
  src/main/resources/application.yml
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationServiceTest.java
  src/test/java/com/goorm/friendchise/domain/notification/domain/NotificationTest.java
  src/test/java/com/goorm/friendchise/domain/notification/infrastructure/FakeNotificationRepository.java
  src/test/java/com/goorm/friendchise/domain/promotion/application/PromotionServiceTest.java
  src/test/java/com/goorm/friendchise/domain/promotion/domain/PromotionTest.java
  src/test/java/com/goorm/friendchise/domain/promotion/infrastructure/FakePromotionRepository.java
Labels: feat

#18 Fix/dev-jap-hotfix
  src/main/java/com/goorm/friendchise/FriendchiseApplication.java
  src/main/resources/application.yml
Labels: bug

#19 Feature/일일매출 기능 구현
  build.gradle
  src/main/java/com/goorm/friendchise/domain/store/application/SalesService.java
  src/main/java/com/goorm/friendchise/domain/store/application/StoreService.java
  src/main/java/com/goorm/friendchise/domain/store/domain/Sales.java
  src/main/java/com/goorm/friendchise/domain/store/domain/Store.java
  src/main/java/com/goorm/friendchise/domain/store/dto/SalesDetailedResDto.java
  src/main/java/com/goorm/friendchise/domain/store/dto/SalesReqDto.java
  src/main/java/com/goorm/friendchise/domain/store/dto/SalesResDto.java
  src/main/java/com/goorm/friendchise/domain/store/dto/StoreReqDto.java
  src/main/java/com/goorm/friendchise/domain/store/dto/res/KakaoApiAddressResDto.java
  src/main/java/com/goorm/friendchise/domain/store/dto/res/KakaoApiRes.java
  src/main/java/com/goorm/friendchise/domain/store/exception/NotFoundAddressException.java
  src/main/java/com/goorm/friendchise/domain/store/exception/SalesNotFoundException.java
  src/main/java/com/goorm/friendchise/domain/store/exception/StoreNotFoundException.java
  src/main/java/com/goorm/friendchise/domain/store/infrastructure/SalesRepository.java
  src/main/java/com/goorm/friendchise/domain/store/presentation/SalesController.java
  src/main/java/com/goorm/friendchise/domain/store/presentation/StoreController.java
  src/main/java/com/goorm/friendchise/global/config/WebClientConfig.java
  src/main/java/com/goorm/friendchise/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: feat

#23 Feature/manager context holder test
  src/test/java/com/goorm/friendchise/domain/manager/application/ManagerServiceTest.java
  src/test/java/com/goorm/friendchise/global/auth/application/AuthServiceTest.java
Labels: enhancement

#28 Refactor/notification transaction handling
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationService.java
  src/main/java/com/goorm/friendchise/domain/notification/domain/NotificationRepository.java
  src/main/java/com/goorm/friendchise/domain/notification/infrastructure/NotificationRepositoryImpl.java
  src/main/java/com/goorm/friendchise/global/config/SecurityConfig.java
  src/test/java/com/goorm/friendchise/domain/notification/infrastructure/FakeNotificationRepository.java
Labels: enhancement

#26 Feature/promotion notification sse connection
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationService.java
  src/main/java/com/goorm/friendchise/domain/notification/domain/Notification.java
  src/main/java/com/goorm/friendchise/domain/notification/domain/NotificationRepository.java
  src/main/java/com/goorm/friendchise/domain/notification/dto/response/NotificationDetailResponse.java
  src/main/java/com/goorm/friendchise/domain/notification/dto/response/ReceivedNotificationResponse.java
  src/main/java/com/goorm/friendchise/domain/notification/infrastructure/JpaNotificationRepository.java
  src/main/java/com/goorm/friendchise/domain/notification/infrastructure/NotificationRepositoryImpl.java
  src/main/java/com/goorm/friendchise/domain/notification/presentation/NotificationController.java
  src/main/java/com/goorm/friendchise/domain/promotion/application/PromotionService.java
  src/main/java/com/goorm/friendchise/domain/promotion/domain/Promotion.java
  src/main/java/com/goorm/friendchise/domain/promotion/presentation/PromotionController.java
  src/main/java/com/goorm/friendchise/global/config/SecurityConfig.java
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationServiceTest.java
  src/test/java/com/goorm/friendchise/domain/notification/infrastructure/FakeNotificationRepository.java
Labels: feat

#33 Feature/jwt reissue
  src/main/java/com/goorm/friendchise/domain/manager/application/ManagerService.java
  src/main/java/com/goorm/friendchise/domain/manager/dto/response/ManagerTokenResponse.java
  src/main/java/com/goorm/friendchise/domain/manager/exception/TokenNotFoundException.java
  src/main/java/com/goorm/friendchise/domain/manager/presentation/ManagerController.java
  src/main/java/com/goorm/friendchise/global/auth/application/AuthService.java
  src/main/java/com/goorm/friendchise/global/auth/domain/RefreshToken.java
  src/main/java/com/goorm/friendchise/global/auth/domain/RefreshTokenRepository.java
  src/main/java/com/goorm/friendchise/global/auth/dto/request/TokenReissueRequest.java
  src/main/java/com/goorm/friendchise/global/auth/dto/response/TokenResponse.java
  src/main/java/com/goorm/friendchise/global/auth/infrastructure/RedisRefreshTokenRepository.java
  src/main/java/com/goorm/friendchise/global/auth/infrastructure/RefreshTokenRepositoryImpl.java
  src/main/java/com/goorm/friendchise/global/exception/ErrorCode.java
  src/test/java/com/goorm/friendchise/domain/manager/application/ManagerServiceTest.java
  src/test/java/com/goorm/friendchise/global/auth/application/AuthServiceTest.java
  src/test/java/com/goorm/friendchise/global/auth/infrastructure/FakeRefreshTokenRepository.java
Labels: feat

#38 레디스 추가
  .github/workflows/deploy.yml
  src/main/java/com/goorm/friendchise/global/config/RedisConfig.java
  src/main/java/com/goorm/friendchise/global/redis/RedisService.java
Labels: feat

#40 매장 매니저 회원가입 시 본사 이름과 인증번호를 확인하는 로직 추가
  src/main/java/com/goorm/friendchise/domain/headquarter/domain/Headquarter.java
  src/main/java/com/goorm/friendchise/domain/manager/application/ManagerService.java
  src/main/java/com/goorm/friendchise/domain/manager/dto/request/ManageCreateRequest.java
  src/main/java/com/goorm/friendchise/domain/manager/exception/HeadquarterAuthNotMatchException.java
  src/main/java/com/goorm/friendchise/global/exception/ErrorCode.java
  src/test/java/com/goorm/friendchise/domain/manager/application/ManagerServiceTest.java
Labels: feat

#44 [Feat] 매장 도메인 구현
  src/main/java/com/goorm/friendchise/domain/headquarter/appilcation/HeadquarterService.java
  src/main/java/com/goorm/friendchise/domain/headquarter/presentation/HeadquarterController.java
  src/main/java/com/goorm/friendchise/domain/manager/domain/Manager.java
  src/main/java/com/goorm/friendchise/domain/store/application/StoreService.java
  src/main/java/com/goorm/friendchise/domain/store/domain/Store.java
  src/main/java/com/goorm/friendchise/domain/store/dto/StoreReqDto.java
  src/main/java/com/goorm/friendchise/domain/store/dto/StoreResDto.java
  src/main/java/com/goorm/friendchise/domain/store/dto/res/KakaoApiAddressResDto.java
  src/main/java/com/goorm/friendchise/domain/store/dto/res/KakaoApiRes.java
  src/main/java/com/goorm/friendchise/domain/store/dto/res/StoreRegisterDto.java
  src/main/java/com/goorm/friendchise/domain/store/exception/NoAuthenticationException.java
  src/main/java/com/goorm/friendchise/domain/store/presentation/StoreController.java
  src/main/java/com/goorm/friendchise/global/exception/ErrorCode.java
  src/test/java/com/goorm/friendchise/domain/headquarter/appilcation/HeadquarterServiceTest.java
Labels: fix, feat, refactor

#41 알림 서비스 로직 분리 및 본사 하위 스토어 조회 테스트 추가
  src/main/java/com/goorm/friendchise/domain/headquarter/application/HeadquarterService.java
  src/main/java/com/goorm/friendchise/domain/headquarter/application/KakaoApiService.java
  src/main/java/com/goorm/friendchise/domain/headquarter/application/OpenAiApiService.java
  src/main/java/com/goorm/friendchise/domain/headquarter/application/StoreRecommendationService.java
  src/main/java/com/goorm/friendchise/domain/headquarter/dto/store/StoreIdDto.java
  src/main/java/com/goorm/friendchise/domain/headquarter/presentation/HeadquarterController.java
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationEventHandler.java
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationManager.java
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationService.java
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationSseService.java
  src/main/java/com/goorm/friendchise/domain/notification/domain/NotificationRepository.java
  src/main/java/com/goorm/friendchise/domain/notification/infrastructure/NotificationRepositoryImpl.java
  src/main/java/com/goorm/friendchise/domain/notification/presentation/NotificationController.java
  src/main/java/com/goorm/friendchise/domain/store/dto/res/StoreRegisterDto.java
  src/test/java/com/goorm/friendchise/domain/headquarter/Item/application/ItemServiceTest.java
  src/test/java/com/goorm/friendchise/domain/headquarter/application/HeadquarterServiceTest.java
  src/test/java/com/goorm/friendchise/domain/headquarter/application/KakaoApiServiceTest.java
  src/test/java/com/goorm/friendchise/domain/headquarter/application/OpenAiApiServiceTest.java
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationEventHandlerTest.java
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationManagerTest.java
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationServiceTest.java
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationSseServiceTest.java
  src/test/java/com/goorm/friendchise/domain/notification/infrastructure/FakeNotificationRepository.java
Labels: feat

#45 JWT에 HQ 매니저 정보 추가
  src/main/java/com/goorm/friendchise/domain/manager/application/ManagerService.java
  src/main/java/com/goorm/friendchise/global/auth/application/AuthService.java
  src/main/java/com/goorm/friendchise/global/auth/jwt/TokenProvider.java
  src/test/java/com/goorm/friendchise/domain/manager/application/ManagerServiceTest.java
  src/test/java/com/goorm/friendchise/global/auth/application/AuthServiceTest.java
Labels: feat

#50 [Bug] test 의존성 삭제 문제 해결
  build.gradle
  src/main/java/com/goorm/friendchise/domain/store/application/StoreService.java
  src/main/java/com/goorm/friendchise/domain/store/dto/StoreReqDto.java
  src/main/java/com/goorm/friendchise/domain/store/dto/res/StoreRegisterDto.java
  src/test/java/com/goorm/friendchise/domain/headquarter/appilcation/HeadquarterServiceTest.java
  src/test/java/com/goorm/friendchise/domain/headquarter/application/HeadquarterServiceTest.java
Labels: fix

#51 Delete src/test/java/com/goorm/friendchise/domain/headquarter/appilca…
  src/test/java/com/goorm/friendchise/domain/headquarter/appilcation/HeadquarterServiceTest.java
Labels: fix

#55 [Fix] 외부 호출 API Convert 값 수정
  src/main/java/com/goorm/friendchise/domain/store/application/StoreService.java
  src/main/java/com/goorm/friendchise/domain/store/dto/res/KakaoApiRes.java
Labels: fix

#61 Headquarter Store cascade 오류 해결
  src/main/java/com/goorm/friendchise/domain/headquarter/application/HeadquarterService.java
  src/main/java/com/goorm/friendchise/domain/store/application/StoreService.java
Labels: fix

#63 프로모션 생성시 ROLE 검증
  src/main/java/com/goorm/friendchise/domain/promotion/application/PromotionService.java
  src/main/java/com/goorm/friendchise/domain/promotion/dto/request/PromotionCreateRequest.java
  src/main/java/com/goorm/friendchise/global/exception/ErrorCode.java
  src/test/java/com/goorm/friendchise/domain/promotion/application/PromotionServiceTest.java
  src/test/java/com/goorm/friendchise/domain/promotion/infrastructure/FakePromotionRepository.java
Labels: feat

#74 각 스토어별 발생한 프로모션에 대해 알림 조회 로직 수정
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationManager.java
  src/main/java/com/goorm/friendchise/domain/notification/domain/NotificationRepository.java
  src/main/java/com/goorm/friendchise/domain/notification/dto/response/ReceivedNotificationResponse.java
  src/main/java/com/goorm/friendchise/domain/notification/infrastructure/JpaNotificationRepository.java
  src/main/java/com/goorm/friendchise/domain/notification/infrastructure/NotificationRepositoryImpl.java
  src/main/java/com/goorm/friendchise/domain/notification/presentation/NotificationController.java
  src/main/java/com/goorm/friendchise/domain/promotion/application/PromotionService.java
  src/main/java/com/goorm/friendchise/global/exception/ErrorCode.java
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationManagerTest.java
  src/test/java/com/goorm/friendchise/domain/notification/infrastructure/FakeNotificationRepository.java
Labels: refactor

#72 인증 진행 후 해당 본사에서 발행한 모든 프로모션 리스트 조회
  src/main/java/com/goorm/friendchise/domain/promotion/application/PromotionService.java
  src/main/java/com/goorm/friendchise/domain/promotion/domain/PromotionRepository.java
  src/main/java/com/goorm/friendchise/domain/promotion/dto/response/PromotionDetailResponse.java
  src/main/java/com/goorm/friendchise/domain/promotion/infrastructure/JpaPromotionRepository.java
  src/main/java/com/goorm/friendchise/domain/promotion/infrastructure/PromotionRepositoryImpl.java
  src/main/java/com/goorm/friendchise/domain/promotion/presentation/PromotionController.java
  src/test/java/com/goorm/friendchise/domain/promotion/infrastructure/FakePromotionRepository.java
Labels: feat

#76 스토어 권한 확인 및 공통 로직 리팩토링
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationEventHandler.java
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationManager.java
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationSseSender.java
  src/main/java/com/goorm/friendchise/domain/notification/domain/Notification.java
  src/main/java/com/goorm/friendchise/domain/notification/presentation/NotificationController.java
  src/main/java/com/goorm/friendchise/global/exception/ErrorCode.java
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationEventHandlerTest.java
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationManagerTest.java
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationSseServiceTest.java
  src/test/java/com/goorm/friendchise/domain/notification/infrastructure/FakeNotificationRepository.java
Labels: feat, refactor

#82 [Feat] Store 단위 테스트 코드 작성
  src/main/java/com/goorm/friendchise/domain/store/application/StoreService.java
  src/test/java/com/goorm/friendchise/domain/store/application/StoreServiceTest.java
Labels: feat, refactor

#80 스토어 매니저 로그인시 해당 스토어 SSE 연결
  src/main/java/com/goorm/friendchise/domain/manager/application/ManagerService.java
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationSseSender.java
  src/main/java/com/goorm/friendchise/domain/notification/presentation/NotificationController.java
  src/main/java/com/goorm/friendchise/domain/store/application/StoreService.java
  src/main/java/com/goorm/friendchise/global/auth/application/AuthService.java
  src/main/java/com/goorm/friendchise/global/auth/jwt/TokenProvider.java
  src/test/java/com/goorm/friendchise/domain/customer/application/CustomerServiceTest.java
  src/test/java/com/goorm/friendchise/domain/headquarter/application/HeadquarterServiceTest.java
  src/test/java/com/goorm/friendchise/domain/manager/application/ManagerServiceTest.java
  src/test/java/com/goorm/friendchise/global/auth/application/AuthServiceTest.java
Labels: feat, refactor

#86 location service 테스트시 storeRepository 추가
  src/test/java/com/goorm/friendchise/domain/location/application/LocationServiceTest.java
Labels: fix

#89 SSE 전송시 페이로드에 알림 ID 추가
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationEventHandler.java
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationSseSender.java
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationEventHandlerTest.java
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationSseServiceTest.java
Labels: feat

#93 chore: 테스트용 CI 추가
  .github/workflows/gradle-test.yml
Labels: documentation

#106 [Refactor] 불필요한 파라미터 삭제
  src/main/java/com/goorm/friendchise/domain/store/application/StoreService.java
  src/main/java/com/goorm/friendchise/domain/store/presentation/StoreController.java
Labels: fix, refactor

#110 fix: locationService와 customerService 순환참조 해결을 위해 CustomerDistanceService 생성
  src/main/java/com/goorm/friendchise/domain/customer/application/CustomerDistanceService.java
  src/main/java/com/goorm/friendchise/domain/location/application/LocationService.java
  src/test/java/com/goorm/friendchise/domain/location/application/LocationServiceTest.java
Labels: fix

#113 Feat/본사 마이페이지에 인증 번호 추가
  src/main/java/com/goorm/friendchise/domain/manager/application/ManagerService.java
  src/main/java/com/goorm/friendchise/domain/manager/dto/response/ManagerDetailResponse.java
  src/test/java/com/goorm/friendchise/domain/headquarter/insfrastructure/FakeHeadquarterRepository.java
  src/test/java/com/goorm/friendchise/domain/manager/application/ManagerServiceTest.java
Labels: feat

#125 프로모션과 알림 도메인 메서드 구조 리팩토링
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationEventHandler.java
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationManager.java
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationSseSender.java
  src/main/java/com/goorm/friendchise/domain/notification/event/NotificationDeletedEvent.java
  src/main/java/com/goorm/friendchise/domain/notification/event/NotificationReadEvent.java
  src/main/java/com/goorm/friendchise/domain/promotion/application/PromotionService.java
  src/main/java/com/goorm/friendchise/domain/promotion/domain/Promotion.java
  src/test/java/com/goorm/friendchise/domain/manager/application/ManagerServiceTest.java
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationEventHandlerTest.java
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationManagerTest.java
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationSseServiceTest.java
  src/test/java/com/goorm/friendchise/domain/promotion/domain/PromotionTest.java
Labels: feat, refactor

#132 Feat/역할 기반으로 인증 인가 설정
  src/main/java/com/goorm/friendchise/domain/headquarter/presentation/HeadquarterController.java
  src/main/java/com/goorm/friendchise/domain/manager/application/ManagerService.java
  src/main/java/com/goorm/friendchise/domain/manager/presentation/ManagerController.java
  src/main/java/com/goorm/friendchise/domain/notification/presentation/NotificationController.java
  src/main/java/com/goorm/friendchise/domain/promotion/presentation/PromotionController.java
  src/main/java/com/goorm/friendchise/domain/store/presentation/SalesController.java
  src/main/java/com/goorm/friendchise/domain/store/presentation/StoreController.java
  src/main/java/com/goorm/friendchise/global/config/SecurityConfig.java
  src/test/java/com/goorm/friendchise/domain/manager/application/ManagerServiceTest.java
Labels: feat

#134 refactor: PAGE 인터페이스 직렬화
  src/main/java/com/goorm/friendchise/global/config/DataWebSupportConfiguration.java
Labels: refactor

#137 SSE connection 역할 검증
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationManager.java
  src/main/java/com/goorm/friendchise/domain/notification/application/NotificationSseSender.java
  src/main/java/com/goorm/friendchise/domain/notification/presentation/NotificationController.java
  src/main/java/com/goorm/friendchise/global/auth/jwt/TokenProvider.java
  src/main/java/com/goorm/friendchise/global/config/SecurityConfig.java
  src/test/java/com/goorm/friendchise/domain/manager/application/ManagerServiceTest.java
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationManagerTest.java
  src/test/java/com/goorm/friendchise/domain/notification/application/NotificationSseServiceTest.java
Labels: feat
